// Generated by https://quicktype.io

class Product {
  int id;
  String title;
  double price;
  int category;
  String description;
  List<String> images;

  Product({
    required this.id,
    required this.title,
    required this.price,
    required this.category,
    required this.description,
    required this.images,
  });
}
